env:
  MAKE: make

clone_template: &CLONE_TEMPLATE
  # need to supersede Cirrus CI-specific git clone with a regular git client
  clone_script: |
    if [ "$CIRRUS_OS" = 'darwin' ]; then
      brew install git
    elif [ "$CIRRUS_OS" = 'freebsd' ]; then
      pkg install -y git
    elif [ -n "$(command -v zypper)" ]; then
      zypper install -y git
    elif [ -n "$(command -v apt-get)" ]; then
      apt-get update
      apt-get -y install git
    else
      yum install -y git
    fi
    if [ -z "$CIRRUS_PR" ]; then
      git clone --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
    else
      git clone https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
    fi
    cd $CIRRUS_WORKING_DIR
    if [ -n "$CIRRUS_PR" ]; then
      git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
    fi
    git reset --hard $CIRRUS_CHANGE_IN_REPO

artifacts_template: &ARTIFACTS_TEMPLATE
  always:
    log_artifacts:
      path: modules.log
      type: text/plain
    installlog_artifacts:
      path: install.log
      type: text/plain

build_install_test_template: &BUILD_INSTALL_TEST_TEMPLATE
  build_script:
    - $MAKE
  test_script: |
    if [ -n "$TEST_SPECIFIC_CONFIG" ]; then
      $MAKE $TEST_SPECIFIC_CONFIG
    fi
    $MAKE test-deps
    script/mt
    if [ -n "$TEST_SPECIFIC_CONFIG" ]; then
      $MAKE uninstall-testconfig
    fi
  install_script:
    - $MAKE install
  testinstall_script:
    - script/mt install
  uninstall_script:
    - $MAKE uninstall

build_install_xvfbtest_template: &BUILD_INSTALL_XVBFTEST_TEMPLATE
  build_script:
    - $MAKE
  test_script: |
    if [ -n "$TEST_SPECIFIC_CONFIG" ]; then
      $MAKE $TEST_SPECIFIC_CONFIG
    fi
    $MAKE test-deps
    xvfb-run script/mt
    if [ -n "$TEST_SPECIFIC_CONFIG" ]; then
      $MAKE uninstall-testconfig
    fi
  install_script:
    - $MAKE install
  testinstall_script:
    - xvfb-run script/mt install
  uninstall_script:
    - $MAKE uninstall


task:
  << : *CLONE_TEMPLATE
  env:
    MAKE: gmake
  freebsd_instance:
    image_family: freebsd-13-1
    cpu: 1
    memory: 2G
  reqinstall_script: pkg install -y bash wget gmake dejagnu py39-sphinx gzip tcl86 tcl-wrapper autoconf ksh93 zsh fish perl5 python39 ruby cmake R readline
  configure_script:
    - ./configure
  << : *BUILD_INSTALL_TEST_TEMPLATE
  << : *ARTIFACTS_TEMPLATE

task:
  << : *CLONE_TEMPLATE
  env:
    COVERAGE: y
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:latest
  reqinstall_script:
    - brew update
    - brew install md5sha1sum expect dejagnu grep fish r tcl-tk gzip
  configure_script:
    - ./configure --prefix=/tmp/modules --with-loadedmodules=null:dot --with-tcl=/opt/homebrew/lib
  << : *BUILD_INSTALL_TEST_TEMPLATE
  coverage_script:
    - for f in tcl/*.tcl; do script/nglfar2ccov $f; done
    - gcov -o lib envmodules
    - curl -Os https://uploader.codecov.io/latest/macos/codecov
    - chmod +x codecov
    - arch -x86_64 ./codecov -t ${CODECOV_TOKEN}
  << : *ARTIFACTS_TEMPLATE

task:
  << : *CLONE_TEMPLATE
  # change dir to launch tests from path containing specific chars
  env:
    CIRRUS_WORKING_DIR: /tmp/modules-1.2.3+branch_name-91-g6dd3db49
    DEBIAN_FRONTEND: noninteractive
    LANGUAGE: C
    LANG: C
    LC_ALL: C
    TEST_SPECIFIC_CONFIG: install-testmodspath-wild
    EXTRATEST_SOURCESH: y
    TESTSUITE_ENABLE_MODULECACHE: 1
  container:
    image: ubuntu:focal
    cpu: 1
    memory: 2G
  reqinstall_script: |
    # restore manpages subsystem in container
    yes | unminimize || true
    # install requirements
    apt-get update
    apt-get -y install wget expect-dev dejagnu python3-sphinx gzip man-db bash tcsh ksh zsh fish tcl tcl8.6 perl python ruby cmake r-base-core
    # libtclenvmodules build requirements
    apt-get -y install gcc autoconf tcl8.6-dev
    # requirements for source-sh extra tests
    apt-get -y install lsof
  configure_script:
    - ./configure --with-tclsh=tclsh8.6 --prefix /tmp/modules --with-tcl=/usr/lib/tcl8.6 --enable-append-manpath --enable-append-binpath --with-bin-search-path=/usr/bin:/bin --enable-silent-shell-debug-support --enable-windows-support --with-loadedmodules=null:dot --enable-quarantine-support --with-quarantine-vars=LD_LIBRARY_PATH --with-dark-background-colors='hi=1:se=2:er=91:wa=93:mp=1;94:di=94:al=96:sy=95' --enable-foo FOO=bar
  << : *BUILD_INSTALL_TEST_TEMPLATE
  << : *ARTIFACTS_TEMPLATE

task:
  << : *CLONE_TEMPLATE
  env:
    DEBIAN_FRONTEND: noninteractive
    LANGUAGE: C
    LANG: C
    LC_ALL: C
  container:
    image: ubuntu:jammy
    cpu: 1
    memory: 2G
  reqinstall_script: |
    # restore manpages subsystem in container
    yes | unminimize || true
    # install requirements
    apt-get update
    apt-get -y install wget expect-dev dejagnu python3-sphinx gzip man-db bash tcsh ksh zsh fish tcl tcl8.6 perl python3 ruby cmake r-base-core
    # libtclenvmodules build requirements
    apt-get -y install gcc autoconf tcl8.6-dev
    # requirements for source-sh extra tests
    apt-get -y install lsof
  configure_script:
    - ./configure --with-tclsh=tclsh8.6 --prefix='/tmp/mo ules' --with-tcl=/usr/lib/tcl8.6
  << : *BUILD_INSTALL_TEST_TEMPLATE
  << : *ARTIFACTS_TEMPLATE

task:
  << : *CLONE_TEMPLATE
  container:
    matrix:
      image: centos:centos7
      image: rockylinux:8
    cpu: 1
    memory: 2G
  reqinstall_script: |
    . /etc/os-release
    # glob comparison as VERSION_ID equals 8.X on Rocky
    if [[ $VERSION_ID == 8* ]]; then
      sed -i 's|enabled=0|enabled=1|' /etc/yum.repos.d/Rocky-PowerTools.repo
      # specific update of libarchive is required for CMake on EL8.3
      yum update -y libarchive
      # need to pre-install correct module implementation to avoid fetching
      # another one from EPEL (as dependency for R-core) on recent RockyLinux 8
      yum install -y environment-modules
    fi
    if [[ $VERSION_ID == 8* ]]; then
      PYTHON_PKG='python36'
      SPHINX_PKG='python3-sphinx'
    else
      PYTHON_PKG='python'
      SPHINX_PKG='python-sphinx'
    fi
    yum install -y epel-release
    yum install -y tcsh zsh ksh tcl perl $PYTHON_PKG gzip ruby cmake R-core make wget perl $SPHINX_PKG git dejagnu man-db rpm-build bzip2 autoconf gcc tcl-devel
    yum install -y which xorg-x11-server-utils xorg-x11-server-Xvfb
    if [[ $VERSION_ID != 8* ]]; then
      wget -O /etc/yum.repos.d/shells_fish_release_2.repo http://download.opensuse.org/repositories/shells:fish:release:2/CentOS_${VERSION_ID}/shells:fish:release:2.repo
    fi
    yum install -y fish
  configure_script:
    - ./configure --with-loadedmodules=null:dot --enable-quarantine-support --with-quarantine-vars='LD_LIBRARY_PATH LD_PRELOAD' --with-bashcompletiondir=/usr/share/bash-completion/completions --with-fishcompletiondir=/usr/share/fish/vendor_completions.d --with-zshcompletiondir=/usr/share/zsh/site-functions
  # also enable a display on this test case to validate x-resource behavior
  << : *BUILD_INSTALL_XVBFTEST_TEMPLATE
  rpm_script:
    - xvfb-run make srpm rpm
  << : *ARTIFACTS_TEMPLATE

task:
  << : *CLONE_TEMPLATE
  arm_container:
    image: almalinux:9
    cpu: 1
    memory: 2G
  reqinstall_script: |
    dnf install -y dnf-plugins-core epel-release
    dnf config-manager --set-enabled crb
    dnf install -y tcsh zsh ksh fish tcl perl python3 gzip ruby cmake R-core make wget perl python3-sphinx git dejagnu man-db rpm-build bzip2 autoconf gcc tcl-devel procps-ng
  configure_script:
    - ./configure --with-bashcompletiondir=/usr/share/bash-completion/completions --with-fishcompletiondir=/usr/share/fish/vendor_completions.d --with-zshcompletiondir=/usr/share/zsh/site-functions
  # also enable a display on this test case to validate x-resource behavior
  << : *BUILD_INSTALL_TEST_TEMPLATE
  rpm_script:
    - make srpm rpm
  << : *ARTIFACTS_TEMPLATE

task:
  << : *CLONE_TEMPLATE
  container:
    matrix:
      image: opensuse/leap:15.3
    cpu: 1
    memory: 2G
  reqinstall_script: |
    zypper install -y tcsh zsh ksh fish tcl perl python ruby cmake R-core R-core-packages make wget python-Sphinx gzip git dejagnu man net-tools autoconf gcc tcl-devel
    zypper install -y which xrdb xvfb-run
  configure_script:
    - ./configure --enable-versioning --with-loadedmodules=null:dot --with-quarantine-vars='LD_LIBRARY_PATH LD_PRELOAD'
  # also enable a display on this test case to validate x-resource behavior
  << : *BUILD_INSTALL_XVBFTEST_TEMPLATE
  << : *ARTIFACTS_TEMPLATE

# vim:set tabstop=2 shiftwidth=2 expandtab autoindent:
